package com.badgersmc.tsspear.api.evidence;

public enum EvidenceKind {
    IMPOSSIBLE_ACCELERATION,
    FLY_VIOLATION,
    SPEED_VIOLATION,
    JESUS_VIOLATION,
    SCAFFOLD_VIOLATION,
    REACH_EXCESS,
    KILL_AURA_PATTERN,
    AIM_SNAP,
    VELOCITY_ANOMALY,
    AUTO_CLICKER_PATTERN,
    FAST_BREAK,
    FAST_PLACE,
    XRAY_HEURISTIC,
    BAD_PACKET,
    BLINK,
    NOSLOW,
    TIMER,
    MACRO_PATTERN,
    INVALID_INTERACT,
    LAG_SPIKE,
    TELEPORT,
    CHECK_FAILURE
}