package com.badgersmc.tsspear.application.config;

public record TSSpearSettings(
    double maxAcceleration,
    double maxSpeed,
    double maxReach,
    int maxAirTicks,
    int killAuraWindowTicks,
    int killAuraVictimThreshold,
    double maxKnockbackDamageRatio,
    int lagThresholdMs,
    double contradictionMultiplier,
    double tensionSensitivity,
    double alertThreshold,
    double confidenceEpsilon,
    double evidencePersistThreshold,
    int workerThreads,
    long evidenceDedupeWindowMs,
    int storageBatchSize,
    long storageFlushIntervalMs,
    int replayRingBufferSeconds,
    int replayTicksPerSecond,
    int continuousCaptureSeconds,
    boolean objectPoolingEnabled,
    int graphNodePoolSize,
    int evidenceBuilderPoolSize,
    int movementScratchPoolSize,
    int graphPropagationBatchSize,
    int blinkMinIntervalMs,
    double badPacketPositionThreshold,
    int mlExportWindowSeconds,
    String mlInferenceProvider,
    double mlRuleBasedCheatingThreshold,
    double mlRuleBasedSuspiciousThreshold
) {
    public static TSSpearSettings defaults() {
        return new TSSpearSettings(
            0.52,
            0.65,
            3.2,
            40,
            10,
            3,
            0.5,
            200,
            0.85,
            1.2,
            0.65,
            0.005,
            0.25,
            2,
            500,
            100,
            50,
            30,
            20,
            300,
            true,
            512,
            256,
            128,
            16,
            40,
            0.5,
            300,
            "rule-based",
            0.65,
            0.40
        );
    }
}